<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>false</IsAspireHost>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" Version="9.5.1" />
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.1" />
    <PackageReference Include="Aspire.Hosting.Azure.Functions" Version="9.5.1-preview.1.25502.11" />
    <PackageReference Include="Aspire.Hosting.Azure.Storage" Version="9.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../azure-functions/MicrosoftUpdateFunctions.csproj" />
  </ItemGroup>

</Project>